services:
  dev-db:
    image: postgres:latest
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DATABASE=nestjs-authentication-cookie
